spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/own_blog_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 520xy1314
mybatis:
  type-aliases-package: com.imnu.pojo   #设置别名
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件

logging: #日志级别
  level:
    root: info
    com.imnu: debug
    com.imnu.dao: debug
  file:
    path: log/blog-dev.log

comment.avatar: /images/avatar.jpg

server:
  port: 82